spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=root

server.port=8081

spring.datasource.url=http:mysql://localhost:3305/testdb
spring.datasource.password=abc
spring.datasource.username=egf

spring.jpa.hibernate.ddl0