spring.application.name=SpringBootOAuth2Resource

server.port=8087
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/master
spring.security.auth2.resourceserver.jwt.jwt-set-uri=http://localhost:7080/realms/master/protocol/openid-connect/certs
#spring.main.web-application-type=reactive 